from django.urls import path

from .views import (
    StudentCreateView, 
    StudentListView, 
    StudentDetailView,
    StudentDeleteView,
    CompanyCreateView, 
    CompanyListView, 
    CompanyDetailView,
    CompanyDeleteView,
    InvestorCreateView, 
    InvestorListView, 
    InvestorDetailView,
    InvestorDeleteView,
    EntrepeneurCreateView, 
    EntrepeneurListView, 
    EntrepeneurDetailView,
    EntrepeneurDeleteView,
    sendCountOfUsers,
    sendFilteredEntrepreneursByMonth,
    sendFilteredStudentsByDay,
    sendFilteredStudentsAddedByMonth,
    sendFilteredEnterpreunerGenderBreakup
)

urlpatterns = [
    path('student/<int:id>/', StudentDetailView.as_view()),
    path('student/', StudentCreateView.as_view()),
    path('students-all/', StudentListView.as_view()),
    path('student/<int:id>/delete/', StudentDeleteView.as_view()),
    path('company/<int:id>/', CompanyDetailView.as_view()),
    path('company/', CompanyCreateView.as_view()),
    path('company/<int:id>/', CompanyDetailView.as_view()),
    path('companies-all/', CompanyListView.as_view()),
    path('company/<int:id>/delete/', CompanyDeleteView.as_view()),
    path('investor/<int:id>/', InvestorDetailView.as_view()),
    path('investor/', InvestorCreateView.as_view()),
    path('investor-all/', InvestorListView.as_view()),
    path('investor/<int:id>/delete/', InvestorDeleteView.as_view()),
    path('entrepeneur/<int:id>/', EntrepeneurDetailView.as_view()),
    path('entrepeneur/', EntrepeneurCreateView.as_view()),
    path('entrepeneur-all/', EntrepeneurListView.as_view()),
    path('entrepeneur/<int:id>/delete/', EntrepeneurDeleteView.as_view()),
    path('count/', sendCountOfUsers),
    path('entrepreneurs-by-month/', sendFilteredEntrepreneursByMonth),
    path('students-by-day/', sendFilteredStudentsByDay),
    path('students-added-by-month/', sendFilteredStudentsAddedByMonth),
    path('entrepreneur-gender-breakup/', sendFilteredEnterpreunerGenderBreakup),
]
